### ISSUE TITLE
Fallback for Open Graph Image not working

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#142]
(Using version 2.2.0)

I have a document type "Product Series", with an image property named "Banner Image".  I set the SEO Open Graph Image field to check "BannerImage":  
![image](https://user-images.githubusercontent.com/8241300/210035894-bacb7113-fb71-4450-9d01-c0068386d91e.png)

My Product Series has a Banner Image set:  
![image](https://user-images.githubusercontent.com/8241300/210035936-d4204688-2782-44cd-80c7-e4459da75047.png)

Open Graph Title/Description use their fallback values correctly, but Image says none found:  
![image](https://user-images.githubusercontent.com/8241300/210035970-d4ff845e-8941-48fb-9594-de6636052853.png)

Does it need a specific Property Type?  I'm just using a standard `Umbraco.MediaPicker3` ("Optional" just means it allows 0-1 images):  
![image](https://user-images.githubusercontent.com/8241300/210036013-16959e89-bbe2-4a0e-8c73-d96cea72bf93.png)

**Comment by patrickdemooij9** [comment]
That configuration should indeed be fine. I'll take a look at what is going wrong here

**Comment by patrickdemooij9** [comment]
Fixed by https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/147. Will be released the coming weekend

**Comment by ianleeder** [comment]
I appreciate the work and fast turnaround @patrickdemooij9.  But I've just upgraded and still have the same issue.  Still no fallback image, and still no `og:image` meta tag being rendered after explicitly setting an image.

Is there any debug I can do to help?  Database snooping?  I'm not sure where SEO settings are saved.

These are the installed versions on my site  
![image](https://user-images.githubusercontent.com/8241300/212792282-7bf641be-8d71-4df1-a534-88d548d62fad.png)

**Comment by patrickdemooij9** [comment]
Hmm, that is strange. I'll take a look at this tonight and will probably send you some queries so that I can see what your data looks like in the database

**Comment by patrickdemooij9** [comment]
@ianleeder I think I figured out where the issue is at, but just to be sure could you add this to your appsettings.json?
```
"SeoToolkit": {
    "MetaFields": {
      "OpenGraphCropAlias": ""
    }
  }
```

By default the system will try to use a crop, but if you don't have it defined it will not be able to resolve the media URL correctly. I think this is happening in your situation, but I want to double-check before doing another release to fix this.

**Comment by ianleeder** [comment]
Oh yeah.  That made a difference  
![image](https://user-images.githubusercontent.com/8241300/213094145-61255928-beef-4376-ba17-ce698e73ac88.png)

```
<meta property="og:image" content="https://localhost:44369/media/f0gnxoxg/welcome-home-woo.jpg?rnd=133172341702770000">
```

**Comment by patrickdemooij9** [comment]
Great! Then I'll be able to push the fix to the newest version soon

**Comment by robertjf** [comment]
@patrickdemooij9 any news on this?  I'll apply the work around, but have noticed this issue as well...

**Comment by patrickdemooij9** [comment]
Hi, sorry for the delay.
I'll be making another release this weekend with this fix and some other ones as well

**Comment by patrickdemooij9** [comment]
Again, sorry for the long delay on the fix here. This should now be fixed in the latest release 2.3.0 & 3.1.0 (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.1.0)

**Comment by ianleeder** [comment]
Hey man, no judgement on the delay.  For open source software, this exceeds expectations.  I just appreciate the effort you've put in.  Thanks.

And I can confirm it's working correctly now.
